config/routes.rb
Rails.application.routes.draw do
  #get 'password_resets/new'

  #get 'password_resets/edit'

  root   'welcome#index'
  get    '/home',    to: 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :jobs do
    member do
      post :join
      post :quit
    end

    collection do
      get :search
      get :developer
      get :healthcare
      get :customer_service
      get :sales_marketing
      get :legal
      get :non_profit
      get :human_resource
      get :design
    end

    resources :resumes
    resources :posts
  end

  namespace :account do
    resources :attention_jobs
    resources :posts
  end

   namespace :admin do
     resources :jobs do
       member do
         post :publish
         post :hide
       end

       resources :resumes
     end
   end

end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :city, presence: true, length: { maximum: 40 }
  validates :company, presence: true, length: { maximum: 40 }
  validates :category, presence: true, length: { maximum: 40 }


  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  belongs_to :user, required: false
  # 如果user_id 不填会一直报错rollback transaction网上查找发现, require: false 可以解决
  has_many :posts
  has_many :resumes
  has_many :job_relationships
  has_many :members, through: :job_relationships, source: :user

  # Scope #
  scope :recent, -> { order("created_at DESC")}
  scope :published, -> { where(:is_hidden => false)}
  scope :random5, -> { limit(5).order("RANDOM()") }

end

app/controllers/account/job_controller.rb
class Account::JobController < ApplicationController
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin
  layout "admin"

  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.all.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!

    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :city, :company, :category, :is_hidden)
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :update, :edit, :destroy, :join, :quit]
  before_action :validate_search_key, only: [:search]

  def show
    @job = Job.find(params[:id])
    @user = @job.user

    @category = @job.category
    # 随机推荐5个相同类型的职位（去除当前职位） #
    @sames = Job.where(:is_hidden => false, :category => @job.category).where.not(:id => @job.id ).random5
    # 搜索该用户投递此职位的简历数量 #
    @resumes = Resume.where(:job => @job, :user => current_user)

    if @job.is_hidden
      flash[:warning] = "该项目已归档！"
      redirect_to root_path
    end
    @posts = @job.posts.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def index

    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      current_user.join!(@job)
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to jobs_path
  end

  #关注项目
  def join
   @job = Job.find(params[:id])

    if !current_user.is_member_of?(@job)
      current_user.join!(@job)
      flash[:notice] = "成功关注该项目！"
    else
      flash[:warning] = "已经关注该项目！"
    end

    redirect_to job_path(@job)
  end

  #取消关注项目
  def quit
    @job = Job.find(params[:id])

    if current_user.is_member_of?(@job)
      current_user.quit!(@job)
      flash[:alert] = "取消关注该项目！"
    else
      flash[:warning] = "未关注该项目！"
    end

    redirect_to job_path(@job)
  end

  def developer
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "developer").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def healthcare
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs =  Job.published.where(:category => "healthcare").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def customer_service
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "customer-service").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def sales_marketing
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "sales-marketing").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def legal
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "legal").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def non_profit
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "non-profit").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def human_resource
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "human-resource").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def design
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "design").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def search
    if @query_string.present?
      search_result = Job.published.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.paginate(:page => params[:page], :per_page => 5 )
    end
  end


  protected

    def validate_search_key
      @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
      @search_criteria = search_criteria(@query_string)
    end


    def search_criteria(query_string)
      { :title_cont => query_string }
    end

  private

  def job_params
    params.require(:job).permit(:title, :description, :city, :company, :category,:is_hidden)
  end

end

app/helpers/account/job_helper.rb
module Account::JobHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end


  # 判断是否投递过简历icon #
  def render_job_resumes(job)
    if job.resumes.count > 0
      "fa fa-envelope-open-o"
    else
      "fa fa-envelope-o"
    end
  end

  # 判断是否有人收藏icon #
  def render_job_collections(job)
    if job.job_relationship.count > 0
      "fa fa-heart"
    else
      "fa fa-heart-o"
    end
  end

  def render_highlight_content(job,query_string)
    excerpt_cont = excerpt(job.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/views/jobs/customer_service.html.erb
<!--=== 工作列表 ===-->

<% provide(:title, "项目列表") %>

<div class="pull-right">
  <%= link_to('<span class="glyphicon glyphicon-gift">创建新项目'.html_safe,
            new_job_path, class: "btn btn-success btn-lg btn3d")%>
</div>
<p></p>

<div class="text-center">
  <h1><strong>项目列表</strong></h1>
</div>


<div class="row ">
    <div class="col-md-9 job-content">
        <% @jobs.each do |job| %>
          <div class=" job-box">
            <% if @jobs.length > 0 %>
                <div >
                    <h4><strong><%= link_to(job.title, job_path(job)) %></strong></h4>
                </div>
                <div >
                    <p style="width: 800px; overflow: hidden;white-space: nowrap;text-overflow: ellipsis;"><%= job.description %></p>
                    <p><%= link_to( "Read more", job_path(job)) %></p>
                </div>
                <div>
                    <p></p>
                    <p>
                      <sapn class="fa fa-street-view"></sapn> <%= job.city %>|
                      <sapn class="fa fa-calendar"></sapn> <%= job.created_at.strftime("%Y-%m-%d") %>|
                      <sapn class="fa fa-weixin"></sapn> <%= job.posts.count %>|

                      <sapn class="fa fa-tags">Tags : <span class="label label-info"><%= job.company %></span>
                      <a href="#"><span class="label label-success"><%= job.category %></span></a>
                    </p>
                </div>

            <% else %>
            <!--=== 没有职位资料 ===-->
                <div >
                    <h2>此分类暂时没有招聘职位哦，请尝试其他选项。</h2>
                </div>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="col-md-3 side-box">
      <div class="row">
          <div class="col-md-12 suggest-title">
            <h3><sapn class="fa fa-tags"></sapn> <strong>职位推荐</strong></h3>
          </div>
          <div>
              <% @suggests.each do |job| %>
                  <div class="col-xs-10 col-xs-offset-1 suggest-content">
                      <div>
                        <h4>
                          <%= link_to job_path(job), target: "_blank" do %>
                              <%= job.title %> [<%= job.city %>]
                          <% end %>
                        </h4>
                      </div>
                      <div>
                        <p>招募职位：<%= job.category %></p>
                      </div>
                      <div>
                        <p>团队名称：<%= job.company %></p>
                      </div>
                  </div>
              <% end %>
          </div>
      </div>
    </div>
</div>



<!--=== 分页区块 ===-->

  <div class="text-center">
    <%= will_paginate @jobs %>
  </div>

app/views/jobs/design.html.erb
<!--=== 工作列表 ===-->

<% provide(:title, "项目列表") %>

<div class="pull-right">
  <%= link_to('<span class="glyphicon glyphicon-gift">创建新项目'.html_safe,
            new_job_path, class: "btn btn-success btn-lg btn3d")%>
</div>
<p></p>

<div class="text-center">
  <h1><strong>项目列表</strong></h1>
</div>


<div class="row ">
    <div class="col-md-9 job-content">
        <% @jobs.each do |job| %>
          <div class=" job-box">
            <% if @jobs.length > 0 %>
                <div >
                    <h4><strong><%= link_to(job.title, job_path(job)) %></strong></h4>
                </div>
                <div >
                    <p style="width: 800px; overflow: hidden;white-space: nowrap;text-overflow: ellipsis;"><%= job.description %></p>
                    <p><%= link_to( "Read more", job_path(job)) %></p>
                </div>
                <div>
                    <p></p>
                    <p>
                      <sapn class="fa fa-street-view"></sapn> <%= job.city %>|
                      <sapn class="fa fa-calendar"></sapn> <%= job.created_at.strftime("%Y-%m-%d") %>|
                      <sapn class="fa fa-weixin"></sapn> <%= job.posts.count %>|

                      <sapn class="fa fa-tags">Tags : <span class="label label-info"><%= job.company %></span>
                      <a href="#"><span class="label label-success"><%= job.category %></span></a>
                    </p>
                </div>

            <% else %>
            <!--=== 没有职位资料 ===-->
                <div >
                    <h2>此分类暂时没有招聘职位哦，请尝试其他选项。</h2>
                </div>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="col-md-3 side-box">
      <div class="row">
          <div class="col-md-12 suggest-title">
            <h3><sapn class="fa fa-tags"></sapn> <strong>职位推荐</strong></h3>
          </div>
          <div>
              <% @suggests.each do |job| %>
                  <div class="col-xs-10 col-xs-offset-1 suggest-content">
                      <div>
                        <h4>
                          <%= link_to job_path(job), target: "_blank" do %>
                              <%= job.title %> [<%= job.city %>]
                          <% end %>
                        </h4>
                      </div>
                      <div>
                        <p>招募职位：<%= job.category %></p>
                      </div>
                      <div>
                        <p>团队名称：<%= job.company %></p>
                      </div>
                  </div>
              <% end %>
          </div>
      </div>
    </div>
</div>



<!--=== 分页区块 ===-->

  <div class="text-center">
    <%= will_paginate @jobs %>
  </div>

app/views/jobs/developer.html.erb
<!--=== 工作列表 ===-->

<% provide(:title, "项目列表") %>

<div class="pull-right">
  <%= link_to('<span class="glyphicon glyphicon-gift">创建新项目'.html_safe,
            new_job_path, class: "btn btn-success btn-lg btn3d")%>
</div>
<p></p>

<div class="text-center">
  <h1><strong>项目列表</strong></h1>
</div>


<div class="row ">
    <div class="col-md-9 job-content">
        <% @jobs.each do |job| %>
          <div class=" job-box">
            <% if @jobs.length > 0 %>
                <div >
                    <h4><strong><%= link_to(job.title, job_path(job)) %></strong></h4>
                </div>
                <div >
                    <p style="width: 800px; overflow: hidden;white-space: nowrap;text-overflow: ellipsis;"><%= job.description %></p>
                    <p><%= link_to( "Read more", job_path(job)) %></p>
                </div>
                <div>
                    <p></p>
                    <p>
                      <sapn class="fa fa-street-view"></sapn> <%= job.city %>|
                      <sapn class="fa fa-calendar"></sapn> <%= job.created_at.strftime("%Y-%m-%d") %>|
                      <sapn class="fa fa-weixin"></sapn> <%= job.posts.count %>|

                      <sapn class="fa fa-tags">Tags : <span class="label label-info"><%= job.company %></span>
                      <a href="#"><span class="label label-success"><%= job.category %></span></a>
                    </p>
                </div>

            <% else %>
            <!--=== 没有职位资料 ===-->
                <div >
                    <h2>此分类暂时没有招聘职位哦，请尝试其他选项。</h2>
                </div>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="col-md-3 side-box">
      <div class="row">
          <div class="col-md-12 suggest-title">
            <h3><sapn class="fa fa-tags"></sapn> <strong>职位推荐</strong></h3>
          </div>
          <div>
              <% @suggests.each do |job| %>
                  <div class="col-xs-10 col-xs-offset-1 suggest-content">
                      <div>
                        <h4>
                          <%= link_to job_path(job), target: "_blank" do %>
                              <%= job.title %> [<%= job.city %>]
                          <% end %>
                        </h4>
                      </div>
                      <div>
                        <p>招募职位：<%= job.category %></p>
                      </div>
                      <div>
                        <p>团队名称：<%= job.company %></p>
                      </div>
                  </div>
              <% end %>
          </div>
      </div>
    </div>
</div>



<!--=== 分页区块 ===-->

  <div class="text-center">
    <%= will_paginate @jobs %>
  </div>

app/views/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title, :label => "项目名称" %>
<%= f.input :description, :label => "项目描述" %>
<%= f.input :city, :label => "工作城市" %>
<%= f.input :company, :label => "团队名称" %>
<%= f.input :category, :collection => ["developer","healthcare", "customer-service", "sales-marketing", "legal", "non-profit", "human-resource", "design"], :selected => "developer", :label => "需求专业" %>

<%= f.submit "创建项目", :disable_with => 'Submiting...', class: "btn btn-primary" %>
<% end %>

app/views/jobs/healthcare.html.erb
<!--=== 工作列表 ===-->

<% provide(:title, "项目列表") %>

<div class="pull-right">
  <%= link_to('<span class="glyphicon glyphicon-gift">创建新项目'.html_safe,
            new_job_path, class: "btn btn-success btn-lg btn3d")%>
</div>
<p></p>

<div class="text-center">
  <h1><strong>项目列表</strong></h1>
</div>


<div class="row ">
    <div class="col-md-9 job-content">
        <% @jobs.each do |job| %>
          <div class=" job-box">
            <% if @jobs.length > 0 %>
                <div >
                    <h4><strong><%= link_to(job.title, job_path(job)) %></strong></h4>
                </div>
                <div >
                    <p style="width: 800px; overflow: hidden;white-space: nowrap;text-overflow: ellipsis;"><%= job.description %></p>
                    <p><%= link_to( "Read more", job_path(job)) %></p>
                </div>
                <div>
                    <p></p>
                    <p>
                      <sapn class="fa fa-street-view"></sapn> <%= job.city %>|
                      <sapn class="fa fa-calendar"></sapn> <%= job.created_at.strftime("%Y-%m-%d") %>|
                      <sapn class="fa fa-weixin"></sapn> <%= job.posts.count %>|

                      <sapn class="fa fa-tags">Tags : <span class="label label-info"><%= job.company %></span>
                      <a href="#"><span class="label label-success"><%= job.category %></span></a>
                    </p>
                </div>

            <% else %>
            <!--=== 没有职位资料 ===-->
                <div >
                    <h2>此分类暂时没有招聘职位哦，请尝试其他选项。</h2>
                </div>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="col-md-3 side-box">
      <div class="row">
          <div class="col-md-12 suggest-title">
            <h3><sapn class="fa fa-tags"></sapn> <strong>职位推荐</strong></h3>
          </div>
          <div>
              <% @suggests.each do |job| %>
                  <div class="col-xs-10 col-xs-offset-1 suggest-content">
                      <div>
                        <h4>
                          <%= link_to job_path(job), target: "_blank" do %>
                              <%= job.title %> [<%= job.city %>]
                          <% end %>
                        </h4>
                      </div>
                      <div>
                        <p>招募职位：<%= job.category %></p>
                      </div>
                      <div>
                        <p>团队名称：<%= job.company %></p>
                      </div>
                  </div>
              <% end %>
          </div>
      </div>
    </div>
</div>



<!--=== 分页区块 ===-->

  <div class="text-center">
    <%= will_paginate @jobs %>
  </div>

app/views/jobs/index.html.erb
<!--=== 工作列表 ===-->

<% provide(:title, "项目列表") %>

<div class="row">
    <div class="col-md-9 job-content">
        <div class="search-box">
          <div class="col-md-9">
            <div class="nav navbar-nav navbar-left">
              <%= form_tag search_jobs_path , :method => :get do %>
              <div class="input-group" id="search-id" >
                <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="请输入职位信息">
                <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
                </div>
              </div>
              <% end %>
            </div>
          </div>

          <div class="col-md-3">
            <div class="pull-right">
              <%= link_to('<span class="glyphicon glyphicon-gift">创建新项目'.html_safe,
                        new_job_path, class: "btn btn-success btn-sm ")%>
            </div>
          </div>
        </div>
        <% @jobs.each do |job| %>
          <div class=" job-box">

            <% if @jobs.length > 0 %>
                <div >
                    <h4><strong><%= link_to(job.title, job_path(job)) %></strong></h4>
                </div>
                <div >
                    <p style="width: 600px; overflow: hidden;white-space: nowrap;text-overflow: ellipsis;"><%= job.description %></p>
                    <p><%= link_to( "Read more", job_path(job)) %></p>
                </div>
                <div>
                    <p></p>
                    <p>
                      <sapn class="fa fa-street-view"></sapn> <%= job.city %>|
                      <sapn class="fa fa-calendar"></sapn> <%= job.created_at.strftime("%Y-%m-%d") %>|
                      <sapn class="fa fa-weixin"></sapn> <%= job.posts.count %>|

                      <sapn class="fa fa-tags">Tags : <span class="label label-info"><%= job.company %></span>
                      <a href="#"><span class="label label-success"><%= job.category %></span></a>
                    </p>
                </div>

            <% else %>
            <!--=== 没有职位资料 ===-->
                <div >
                    <h2>此分类暂时没有招聘职位哦，请尝试其他选项。</h2>
                </div>
            <% end %>
          </div>
        <% end %>
    </div>

    <div class="col-md-3 side-box">
      <div class="row">
          <div class="col-md-12 suggest-title">
            <h3><sapn class="fa fa-tags"></sapn> <strong>职位推荐</strong></h3>
          </div>
          <div>
              <% @suggests.each do |job| %>
                  <div class="col-xs-10 col-xs-offset-1 suggest-content">
                      <div>
                        <h4>
                          <%= link_to job_path(job), target: "_blank" do %>
                              <%= job.title %> [<%= job.city %>]
                          <% end %>
                        </h4>
                      </div>
                      <div>
                        <p>招募职位：<%= job.category %></p>
                      </div>
                      <div>
                        <p>团队名称：<%= job.company %></p>
                      </div>
                  </div>
              <% end %>
          </div>
      </div>
    </div>
</div>



<!--=== 分页区块 ===-->

  <div class="text-center">
    <%= will_paginate @jobs %>
  </div>

app/views/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for @job do |f| %>

<%= f.input :title, :label => "项目名称" %>
<%= f.input :description, :label => "项目描述" %>
<%= f.input :city, :label => "工作城市" %>
<%= f.input :company, :label => "团队名称" %>
<%= f.input :category, :collection => ["developer","healthcare", "customer-service", "sales-marketing", "legal", "non-profit", "human-resource", "design"], :selected => "developer", :label => "需求专业" %>
<!-- <%= f.input :is_hidden %> 新增的项目默认隐藏，网站管理员审核后，可以公开-->

  <%= f.submit "创建项目", :disable_with => 'Submiting...', class: "btn btn-primary" %>
<% end %>

app/views/jobs/show.html.erb
<% provide(:title, "项目展示") %>

<div class="panel panel-info">
  <div class="panel-heading">
    <h1 ><%= @job.title %></h1>
  </div>

  <div class="panel-body">

    <div class="job-content">
      <!--======== Start - Jobs上方区块 =========-->
      <div class="row">
        <!--======== Start - 左侧区块 =========-->
        <div class="col-md-8 col-md-offset-1 job-info-box">
          <p>
            <span class="fa fa-building"><%= @job.company %></span>/
            <span class="fa fa-map-marker"><%= @job.city %></span>  /
            <span class="fa fa-list"> <%= @job.category %></span>
           </p>
          <p class="created"><%= @job.created_at.strftime("%Y-%m-%d") %> <span class="website">发布于扬帆社区</span></p>
        </div>
        <!--======== End - 左侧区块 =========-->

        <!--======== Start - 右侧区块 =========-->
        <div class="col-md-4 job-action-box">
          <div>
            <!-- 判断是否已收藏 -->
            <% if current_user && current_user.is_member_of?(@job) %>
              <%= link_to quit_job_path(@job), method: :post, class: "btn btn-lg btn-primary" do %>
                <span class="fa fa-star"></span> 已收藏
              <% end %>
            <% else %>
              <%= link_to join_job_path(@job), method: :post, class: "btn btn-lg btn-default" do %>
                <span class="fa fa-star-o"></span> 收藏
              <% end %>
            <% end %>
          </div>
          <div>
            <!--==== 判断是否已投过简历 ====-->
            <% if @resumes.length > 0 %>
              <%= link_to("已投过简历", '#', class: "btn btn-lg btn-danger") %>
            <% else %>
              <%= link_to("投递简历", new_job_resume_path(@job), class: "btn btn-lg btn-success") %>
            <% end %>
          </div>
        </div>
        <!--======== End - 右侧区块 =========-->
      </div>
      <!--======== End - Jobs上方区块 =========-->
    <hr style="width:85%" />
      <!--======== Start - Jobs下方区块 =========-->
      <div class="row">
        <!--======== Start - 左侧区块 =========-->
        <div class="col-md-7 col-md-offset-1 job-content-box">
          <div class="content-info">
            <h4>项目描述：</h4>
            <p><%= simple_format(@job.description) %></p>
          </div>
          <hr />
          <div class="mail-info">
            <h4>联络信息：</h4>
            <p class="email"><span class="glyphicon glyphicon-user"></span>  <%= link_to @user.name, @user %></p>
            <p class="email"><span class="glyphicon glyphicon-envelope"></span>  <%= link_to @user.email, @user %></p>
          </div>
        </div>
        <!--======== End - 左侧区块 =========-->

        <!--======== Start - 右侧区块 =========-->
        <% if @sames.length > 0 %>
        <div class="col-md-3">
          <div class="same-box">
            <div class="title">
              <span>相似职位</span>
            </div>
            <% @sames.each do |job| %>
              <div class="same-content">
                <div>
                  <h3>
                    <%= link_to job_path(job), target: "_blank" do %>
                      <%= job.title %> [<%= job.city %>]
                    <% end %>
                  </h3>
                </div>

                <div><span><%= job.company %></span></div>
              </div>
            <% end %>
          </div>
        </div>
        <% end %>
        <!--======== End - 右侧区块 =========-->
      </div>
      <!--======== End - Jobs下方区块 =========-->
    </div>
    <hr style="width:85%"/>

    <div class="container">
        <div class="col-lg-11 col-sm-12 text-center">

        <div class="well">
            <h4>What is on your mind?</h4>


            <div class="input-group">
                <input  type="text" id="userComment" class="form-control input-lg chat-input" placeholder="Write your message here..." />
        	    <span class="input-group-btn" onclick="addComment()">
                <%= link_to('<span class="glyphicon glyphicon-comment">发表评论'.html_safe,new_job_post_path(@job), class: "btn btn-primary btn-lg ")%>
                </span>
            </div>

        <hr style="width:85%"/>
          <ul data-brackets-id="12674" id="sortable" class="list-unstyled ui-sortable">

            <div class="job-posts">
              <% @posts.each do |post| %>
                  <li >
                    <%= link_to gravatar_for( post.user, size: 50), post.user %>
                    <p>
                    <span class="user pull-left"><%= link_to post.user.name, post.user %></span>

                    <span class="glyphicon glyphicon-time pull-right">
                      Posted <%= time_ago_in_words(post.created_at) %> ago.
                    </span><br/>

                    <span class="content pull-left">
                      <%= post.content %>
                    </span><br/>
                    </p>
                  </li>
                  <hr style="width:100%"/>
              <% end %>
            </div>

          </ul>
        </div>
      </div>
    </div>
  </div>
</div>