config/routes.rb
Rails.application.routes.draw do
  #get 'password_resets/new'

  #get 'password_resets/edit'

  root   'welcome#index'
  get    '/home',    to: 'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  resources :jobs do
    member do
      post :join
      post :quit
    end

    collection do
      get :search
      get :developer
      get :healthcare
      get :customer_service
      get :sales_marketing
      get :legal
      get :non_profit
      get :human_resource
      get :design
    end

    resources :resumes
    resources :posts
  end

  namespace :account do
    resources :attention_jobs
    resources :posts
  end

   namespace :admin do
     resources :jobs do
       member do
         post :publish
         post :hide
       end

       resources :resumes
     end
   end

end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :city, presence: true, length: { maximum: 40 }
  validates :company, presence: true, length: { maximum: 40 }
  validates :category, presence: true, length: { maximum: 40 }


  def publish!
    self.is_hidden = false
    self.save
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  belongs_to :user, required: false
  # 如果user_id 不填会一直报错rollback transaction网上查找发现, require: false 可以解决
  has_many :posts
  has_many :resumes
  has_many :job_relationships
  has_many :members, through: :job_relationships, source: :user

  # Scope #
  scope :recent, -> { order("created_at DESC")}
  scope :published, -> { where(:is_hidden => false)}
  scope :random5, -> { limit(5).order("RANDOM()") }

end

app/controllers/account/job_controller.rb
class Account::JobController < ApplicationController
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :update, :edit, :destroy]
  before_action :require_is_admin
  layout "admin"

  def show
    @job = Job.find(params[:id])
  end

  def index
    @jobs = Job.all.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      redirect_to admin_jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to admin_jobs_path
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!

    redirect_to :back
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!

    redirect_to :back
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :city, :company, :category, :is_hidden)
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :update, :edit, :destroy, :join, :quit]
  before_action :validate_search_key, only: [:search]

  def show
    @job = Job.find(params[:id])
    @user = @job.user

    @category = @job.category
    # 随机推荐5个相同类型的职位（去除当前职位） #
    @sames = Job.where(:is_hidden => false, :category => @job.category).where.not(:id => @job.id ).random5
    # 搜索该用户投递此职位的简历数量 #
    @resumes = Resume.where(:job => @job, :user => current_user)

    if @job.is_hidden
      flash[:warning] = "该项目已归档！"
      redirect_to root_path
    end
    @posts = @job.posts.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def index

    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.recent.paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)

    if @job.save
      current_user.join!(@job)
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])

    @job.destroy

    redirect_to jobs_path
  end

  #关注项目
  def join
   @job = Job.find(params[:id])

    if !current_user.is_member_of?(@job)
      current_user.join!(@job)
      flash[:notice] = "成功关注该项目！"
    else
      flash[:warning] = "已经关注该项目！"
    end

    redirect_to job_path(@job)
  end

  #取消关注项目
  def quit
    @job = Job.find(params[:id])

    if current_user.is_member_of?(@job)
      current_user.quit!(@job)
      flash[:alert] = "取消关注该项目！"
    else
      flash[:warning] = "未关注该项目！"
    end

    redirect_to job_path(@job)
  end

  def developer
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "developer").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def healthcare
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs =  Job.published.where(:category => "healthcare").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def customer_service
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "customer-service").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def sales_marketing
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "sales-marketing").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def legal
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "legal").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def non_profit
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "non-profit").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def human_resource
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "human-resource").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def design
    # 随机推荐五个职位 #
    @suggests = Job.published.random5
    @jobs = Job.published.where(:category => "design").recent.paginate(:page => params[:page], :per_page => 5)
  end

  def search
    if @query_string.present?
      search_result = Job.published.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.paginate(:page => params[:page], :per_page => 5 )
    end
  end


  protected

    def validate_search_key
      @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
      @search_criteria = search_criteria(@query_string)
    end


    def search_criteria(query_string)
      { :title_cont => query_string }
    end

  private

  def job_params
    params.require(:job).permit(:title, :description, :city, :company, :category,:is_hidden)
  end

end

app/helpers/account/job_helper.rb
module Account::JobHelper
end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock")
    else
      content_tag(:span, "", :class => "fa fa-globe")
    end
  end


  # 判断是否投递过简历icon #
  def render_job_resumes(job)
    if job.resumes.count > 0
      "fa fa-envelope-open-o"
    else
      "fa fa-envelope-o"
    end
  end

  # 判断是否有人收藏icon #
  def render_job_collections(job)
    if job.job_relationship.count > 0
      "fa fa-heart"
    else
      "fa fa-heart-o"
    end
  end

  def render_highlight_content(job,query_string)
    excerpt_cont = excerpt(job.title, query_string, radius: 500)
    highlight(excerpt_cont, query_string)
  end
end

app/views/admin/jobs/edit.html.erb
<h1> Edit a job </h1>

<%= simple_form_for [:admin, @job ] do |f| %>

<%= f.input :title, :label => "项目名称" %>
<%= f.input :description, :label => "项目描述" %>
<%= f.input :city, :label => "工作城市" %>
<%= f.input :company, :label => "团队名称" %>
<%= f.input :category, :label => "需求专业" %>
<%= f.input :is_hidden %>

  <%= f.submit "创建项目", :disable_with => 'Submiting...', class: "btn btn-primary" %>
<% end %>

app/views/admin/jobs/index.html.erb
<div class="pull-right">
  <%= link_to('<span class="glyphicon glyphicon-gift">创建新项目'.html_safe,
            new_job_path, class: "btn btn-success btn-lg btn3d")%>
</div>

<br><br>

<table class="table table-boldered table-striped custab" >
    <thead>
        <tr>
            <td>项目名称</td>
            <td>收到简历数量</td>
            <td>工作城市</td>
            <td>团队名称</td>
            <td>需求专业</td>
            <td>管理选项</td>
            <td>发布时间</td>
        </tr>
    </thead>

    <% @jobs.each do |job| %>
    <tr>

        <td>
            <%= render_job_status(job) %>

            <%= link_to(job.title, admin_job_path(job)) %>
        </td>
        <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %> </td>
        <td><%= job.city %></td>
        <td><%= job.company %></td>
        <td><%= job.category %></td>

        <td>
            <%= link_to edit_admin_job_path(job), class: "btn btn-xs btn-info" do %><i class="fa fa-pencil"></i><% end %>
            <%= link_to admin_job_path(job), :method => :delete, :class => "btn btn-xs  btn-danger", :data => { :confirm => "Are you sure?" } do %><i class="fa fa-trash-o"></i><% end %>
            <% if job.is_hidden %>
               <%= link_to publish_admin_job_path(job) , :method => :post, :class => "btn btn-xs btn-success" do %><i class="fa fa-eye"></i><% end %>
            <% else %>
               <%= link_to hide_admin_job_path(job), :method => :post,  :class => "btn btn-xs btn-warning" do %><i class="fa fa-eye-slash"></i><% end %>
            <% end %>
        </td>
        <td>
            <%= job.created_at %>
        </td>
    </tr>
    <% end %>
</table>


<div class="text-center">
  <%= will_paginate @jobs %>
</div>

app/views/admin/jobs/new.html.erb
<h1> Add a job </h1>

<%= simple_form_for [:admin,@job] do |f| %>

<%= f.input :title, :label => "项目名称" %>
<%= f.input :description, :label => "项目描述" %>
<%= f.input :city, :label => "工作城市" %>
<%= f.input :company, :label => "团队名称" %>
<%= f.input :category, :label => "需求专业" %>
<%= f.input :is_hidden %>

  <%= f.submit "创建项目", :disable_with => 'Submiting...', class: "btn btn-primary" %>
<% end %>

app/views/admin/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<p>
  <%= simple_format(@job.description) %>

</p>